// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxutqwlnfsjzoxltokcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dXRxd2xuZnNqem94bHRva2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDcxODMsImV4cCI6MjA1MzYyMzE4M30.RWLBnxud7U0F8utcUMmjtxo7u9wsKroeMDvsPY-ZHwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);